import { Sora, JetBrains_Mono } from "next/font/google";
import "./globals.css";
// components
import MainNav from "@/components/MainNav"
import PageTransition from "@/components/PageTransition"
import RectangleTransition from "@/components/RectangleTransition";
import Header from "@/components/Header";

const sora = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-sora",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrains-mono",
});

export const metadata = {
  title: "Harry's World | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sora.variable} ${jetbrainsMono.variable}`}>
      <body className="font-primary antialiased">
        <RectangleTransition />
        <PageTransition>
          <div className="flex h-screen">
            {/* main nav - fixed sidebar */}
            <div className="hidden 2xl:flex w-[185px] h-screen bg-secondary fixed left-0 top-0">
              <MainNav/>
            </div>
            {/* content area - scrollable */}
            <div className="w-full 2xl:ml-[285px] overflow-y-auto">
              <div className="max-w-[1130px] px-[15px] mx-auto">
                <Header/>
                <div>{children}</div>
              </div>
            </div>
          </div>
        </PageTransition>
      </body>
    </html>
  );
}
