import { Sora, JetBrains_Mono } from "next/font/google";
import "./globals.css";
// components
import FloatingDock from "@/components/FloatingDock"
import MobileNav from "@/components/MobileNav"
import PageTransition from "@/components/PageTransition"
import RectangleTransition from "@/components/RectangleTransition";
import CustomCursor from "@/components/CustomCursor";

const sora = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-sora",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrains-mono",
});

export const metadata = {
  title: "Harry's World | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sora.variable} ${jetbrainsMono.variable}`}>
      <body className="font-primary antialiased cursor-none">
        <CustomCursor />
        <RectangleTransition />
        <PageTransition>
          {/* Mobile Navigation */}
          <MobileNav />
          
          {/* Main Content */}
          <div className="w-full min-h-screen">
            <div className="px-6 md:px-10 mx-auto pt-20 md:pt-8 pb-24">
              {children}
            </div>
          </div>
          
          {/* Floating Dock - Desktop Only */}
          <FloatingDock />
        </PageTransition>
      </body>
    </html>
  );
}
